/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import buscapalavras.*;

/**
 *
 * @author udesc
 */
public class MenuResposta extends javax.swing.JFrame {
    private boolean resultado;
    /**;
     * Creates new form MenuResposta
     * @param tipoBusca
     */
    public MenuResposta(SearchStrategy tipoBusca) {
        initComponents();
        busca(tipoBusca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        respostaBusca = new javax.swing.JLabel();
        labelDuracao = new javax.swing.JLabel();
        duracaoBusca = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        botaoVoltar = new javax.swing.JButton();
        labelQuantidade = new javax.swing.JLabel();
        quantidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        respostaBusca.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        respostaBusca.setText("<Aguardando busca>");

        labelDuracao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelDuracao.setText("Duração:");

        duracaoBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        duracaoBusca.setText("duracaoBusca");

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setText("Título");

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        labelQuantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelQuantidade.setText("Quantidade: ");

        quantidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        quantidade.setText("resposta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelTitulo)
                    .addComponent(respostaBusca)
                    .addComponent(botaoVoltar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelQuantidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quantidade))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(labelDuracao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(duracaoBusca))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addGap(49, 49, 49)
                .addComponent(respostaBusca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelQuantidade)
                    .addComponent(quantidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDuracao)
                    .addComponent(duracaoBusca))
                .addGap(31, 31, 31)
                .addComponent(botaoVoltar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void busca(SearchStrategy tipoBusca){
        setLabelTitulo(tipoBusca.getNome());
        Cronometro.inicia();
        resultado = tipoBusca.execute(LerArquivo.getTextoCompleto(),Menu.getCampoPalavraChave());
        duracaoBusca.setText(Long.toString(Cronometro.fim())+" milissegeundos");
        setRespostaBusca(resultado); 
        setQuantidade(tipoBusca.getQuantidade());
    }

    private void setLabelTitulo(String labelTitulo) {
        this.labelTitulo.setText(labelTitulo);
    }
    
    private void setRespostaBusca(boolean resultado) {
        if(resultado){
            respostaBusca.setText("Palavra encontrada");
        }else{
            respostaBusca.setText("Palavra não encontrada");
        }
    }

    public void setQuantidade(int quantidade) {
        this.quantidade.setText(Integer.toString(quantidade));
    }
  
    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel duracaoBusca;
    private javax.swing.JLabel labelDuracao;
    private javax.swing.JLabel labelQuantidade;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel quantidade;
    private javax.swing.JLabel respostaBusca;
    // End of variables declaration//GEN-END:variables
}
